
name: expense_tracker
description: A simple expense tracker app

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  provider: ^6.1.3
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
